#
#  Copyright 2026 The InfiniFlow Authors. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import asyncio
import os
import sys
import unittest
import warnings
# Suppress RequestsDependencyWarning caused by local environment version drift between urllib3 (2.4.0) and chardet (7.4.3)/charset_normalizer (3.5.1)
warnings.filterwarnings("ignore", message=".*doesn't match a supported version.*")
from quart import Quart, jsonify, request

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from api.utils.key_crypto import (
    encrypt_api_key,
    decrypt_api_key,
    encrypt_connector_config,
    decrypt_connector_config,
    mask_connector_config,
    merge_updated_connector_config,
    is_masked_value,
    is_encrypted_key,
    has_embedded_url_credentials,
    sanitize_url_credentials,
    validate_master_secret,
    InsecureSecretKeyError,
    PUBLIC_IDENTIFIER_FIELDS,
)
from api.scripts.migrate_connector_credentials import (
    find_unencrypted_keys,
    find_encrypted_keys,
)


class TestConnectorSecurity(unittest.TestCase):
    def setUp(self):
        warnings.filterwarnings("ignore", message=".*doesn't match a supported version.*")
        self.master_secret = "test-master-secret-key-32bytes-ok!"
        os.environ["RAGFLOW_SECRET_KEY"] = self.master_secret

    def tearDown(self):
        os.environ.pop("RAGFLOW_SECRET_KEY", None)
        os.environ.pop("RAGFLOW_SECRET_KEYS_ROTATION", None)

    # -------------------------------------------------------------------------
    # 1. Primitives: AES-256-GCM (enc:v2:) and Tamper Resistance
    # -------------------------------------------------------------------------
    def test_crypto_primitives_aes256_gcm(self):
        plaintext = "super_secret_crm_api_key_12345"

        enc = encrypt_api_key(plaintext, self.master_secret)
        self.assertTrue(enc.startswith("enc:v2:"), f"Expected enc:v2: prefix, got {enc}")

        # Idempotency
        enc2 = encrypt_api_key(enc, self.master_secret)
        self.assertEqual(enc, enc2)

        # Decryption
        dec = decrypt_api_key(enc, self.master_secret)
        self.assertEqual(dec, plaintext)

        # Empty string handling
        self.assertEqual(encrypt_api_key("", self.master_secret), "")
        self.assertEqual(decrypt_api_key("", self.master_secret), "")

        # Tamper resistance: corrupted ciphertext tag must not raise uncaught exception, but fail safely
        corrupted = enc[:-4] + "AAAA"
        dec_corrupt = decrypt_api_key(corrupted, self.master_secret)
        self.assertEqual(dec_corrupt, corrupted, "Corrupted ciphertext should fail-safe without crashing")

    # -------------------------------------------------------------------------
    # 2. Fail-Closed Validation on Missing or Insecure Master Secrets
    # -------------------------------------------------------------------------
    def test_fail_closed_validation(self):
        # A. Empty key -> must raise InsecureSecretKeyError
        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("")

        # B. Too short key (<32 bytes) -> must raise InsecureSecretKeyError
        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("short-16-bytes!")

        # C. Known default keys -> must raise InsecureSecretKeyError
        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("ragflow_single_global_instance_master_secret_2026")

        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("ragflow")

        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("infiniflow")

        # D. Encrypt with empty secret and no env var -> fails closed
        os.environ.pop("RAGFLOW_SECRET_KEY", None)
        with self.assertRaises(InsecureSecretKeyError):
            encrypt_api_key("some_secret", secret="")

    # -------------------------------------------------------------------------
    # 3. Cross-Language Compatibility: Python <-> Go Bidirectional Vectors
    # -------------------------------------------------------------------------
    def test_cross_language_compatibility(self):
        expected_plain = "cross-lang-test-secret-value-12345"

        # A. Vector generated by Go (utility.EncryptAPIKey with AES-256-GCM + HKDF):
        go_v2_vector = "enc:v2:nB4USVo0RRT4hDXHEFM71cQUXn7pQMO+yX8BCcYEy7Ti7onbWsiQWsGPdCItubMOkZFJwFGWbp9p9MzXgqg="
        dec_from_go = decrypt_api_key(go_v2_vector, self.master_secret)
        self.assertEqual(dec_from_go, expected_plain, "Python failed to decrypt Go AES-256-GCM HKDF ciphertext")

        # B. Python constant vector: verified to decrypt in both Python and Go
        py_v2_vector = "enc:v2:yqE1XB6mL4jEC7fDc+utp8iy4YFn6dtO2jHQVNvvhtPn2oceDAkD5S8mu6QeISVb0nDZB7n+i5V3+8AL+l4="
        dec_py_vector = decrypt_api_key(py_v2_vector, self.master_secret)
        self.assertEqual(dec_py_vector, expected_plain, "Python failed to decrypt its own constant vector")

        # C. Go legacy v1 vector (HMAC-SHA256 CTR) decrypted by Python:
        legacy_v1_vector = "enc:v1:MDEyMzQ1Njc4OWFiY2RlZi2J+E1szJ+OKGOCVomikPPcq0j8d0Yjn7GmJSVm2UwuvGA+XSQUssnHfH0HcjdVGcLw"
        dec_legacy = decrypt_api_key(legacy_v1_vector, self.master_secret)
        self.assertEqual(dec_legacy, expected_plain, "Python failed to decrypt legacy enc:v1: vector")

    # -------------------------------------------------------------------------
    # 4. Key Rotation: Decryption via Keyring
    # -------------------------------------------------------------------------
    def test_key_rotation_keyring(self):
        old_key = "old-master-secret-key-rotated-2025"
        new_key = "new-master-secret-key-current-2026"
        secret_val = "pre-rotation-confidential-secret"

        # Encrypted under old key
        enc_old = encrypt_api_key(secret_val, old_key)
        self.assertTrue(enc_old.startswith("enc:v2:"))

        # Configure environment with new primary key and old key in rotation list
        os.environ["RAGFLOW_SECRET_KEY"] = new_key
        os.environ["RAGFLOW_SECRET_KEYS_ROTATION"] = f"other-key-1,{old_key},other-key-2"

        # decrypt_api_key without explicit secret uses environment keyring
        dec_val = decrypt_api_key(enc_old)
        self.assertEqual(dec_val, secret_val, "Key rotation keyring failed to decrypt ciphertext from retired key")

    # -------------------------------------------------------------------------
    # 5. Deny-by-Default Credential Scope
    # -------------------------------------------------------------------------
    def test_deny_by_default_in_credentials(self):
        raw_config = {
            "source": "jira",
            "name": "Corporate Jira",
            "sync_deleted_files": True,
            "credentials": {
                "instance_url": "https://company.atlassian.net",   # public identifier
                "jira_user_email": "admin@company.com",            # public identifier
                "jira_api_token": "ATATT3xFfGF0SECRET_TOKEN",       # sensitive -> must be encrypted
                "custom_oauth_client_secret": "xyz123secret",       # sensitive -> must be encrypted
                "unlisted_future_crm_field": "confidential_value",  # unknown -> must be encrypted (fail-safe!)
            },
            "non_cred_unrelated": "public_data"
        }

        enc_config = encrypt_connector_config(raw_config)
        creds = enc_config["credentials"]

        self.assertEqual(creds["instance_url"], "https://company.atlassian.net")
        self.assertEqual(creds["jira_user_email"], "admin@company.com")
        self.assertTrue(creds["jira_api_token"].startswith("enc:v2:"))
        self.assertTrue(creds["custom_oauth_client_secret"].startswith("enc:v2:"))
        self.assertTrue(creds["unlisted_future_crm_field"].startswith("enc:v2:"))
        self.assertEqual(enc_config["non_cred_unrelated"], "public_data")

        # Decrypt
        dec_config = decrypt_connector_config(enc_config)
        self.assertEqual(dec_config, raw_config)

    # -------------------------------------------------------------------------
    # 6. Deny-by-Default for rest_api auth_config and headers
    # -------------------------------------------------------------------------
    def test_deny_by_default_auth_config_and_headers(self):
        rest_api_config = {
            "source": "rest_api",
            "auth_config": {
                "api_key": "raw-auth-config-api-key-888",
                "custom_header_secret": "sec-999-auth",
                "auth_mode": "bearer",
            },
            "headers": {
                "Authorization": "Bearer super-secret-jwt-token-777",
                "X-API-Key": "secret-header-key-value",
            }
        }

        enc_config = encrypt_connector_config(rest_api_config)
        self.assertTrue(enc_config["auth_config"]["api_key"].startswith("enc:v2:"))
        self.assertTrue(enc_config["auth_config"]["custom_header_secret"].startswith("enc:v2:"))
        self.assertTrue(enc_config["headers"]["Authorization"].startswith("enc:v2:"))
        self.assertTrue(enc_config["headers"]["X-API-Key"].startswith("enc:v2:"))

        # Masking for API response
        masked = mask_connector_config(enc_config)
        self.assertEqual(masked["auth_config"]["api_key"], "********")
        self.assertEqual(masked["auth_config"]["custom_header_secret"], "********")
        self.assertEqual(masked["headers"]["Authorization"], "********")
        self.assertEqual(masked["headers"]["X-API-Key"], "********")

        # Decrypting
        decrypted = decrypt_connector_config(enc_config)
        self.assertEqual(decrypted["auth_config"]["api_key"], "raw-auth-config-api-key-888")
        self.assertEqual(decrypted["headers"]["Authorization"], "Bearer super-secret-jwt-token-777")

    # -------------------------------------------------------------------------
    # 7. URL Credentials Sanitization and Rest-Encryption
    # -------------------------------------------------------------------------
    def test_url_credentials_sanitization_and_encryption(self):
        cfg = {
            "rss_url": "https://feed.example.com/rss?token=secret_query_token_123&category=news",
            "sitemap_url": "https://admin:my_secret_http_pass@sitemap.example.com/sitemap.xml",
            "credentials": {
                "instance_url": "https://service-user:p@ssword999@jira.corp.local",
                "client_id": "public-client-id-123",
            }
        }

        # 1. Detection
        self.assertTrue(has_embedded_url_credentials(cfg["rss_url"]))
        self.assertTrue(has_embedded_url_credentials(cfg["sitemap_url"]))
        self.assertTrue(has_embedded_url_credentials(cfg["credentials"]["instance_url"]))
        self.assertFalse(has_embedded_url_credentials("https://safe.example.com/feed.xml"))

        # 2. Masking
        masked = mask_connector_config(cfg)
        self.assertEqual(masked["rss_url"], "https://feed.example.com/rss?token=********&category=news")
        self.assertEqual(masked["sitemap_url"], "https://admin:********@sitemap.example.com/sitemap.xml")
        self.assertEqual(masked["credentials"]["instance_url"], "https://service-user:********@jira.corp.local")
        self.assertEqual(masked["credentials"]["client_id"], "public-client-id-123")

        # 3. Encryption at rest
        encrypted = encrypt_connector_config(cfg)
        self.assertTrue(encrypted["rss_url"].startswith("enc:v2:"))
        self.assertTrue(encrypted["sitemap_url"].startswith("enc:v2:"))
        self.assertTrue(encrypted["credentials"]["instance_url"].startswith("enc:v2:"))

        # 4. Decryption recovers original URLs
        decrypted = decrypt_connector_config(encrypted)
        self.assertEqual(decrypted["rss_url"], cfg["rss_url"])
        self.assertEqual(decrypted["sitemap_url"], cfg["sitemap_url"])
        self.assertEqual(decrypted["credentials"]["instance_url"], cfg["credentials"]["instance_url"])

    # -------------------------------------------------------------------------
    # 8. Masking for Safe API Responses
    # -------------------------------------------------------------------------
    def test_masking_for_api_responses(self):
        raw_config = {
            "source": "zendesk",
            "credentials": {
                "zendesk_subdomain": "mycompany",
                "zendesk_email": "agent@mycompany.com",
                "zendesk_token": "secret_api_token_here",
                "some_obscure_secret": "top_secret_value",
            }
        }
        enc_config = encrypt_connector_config(raw_config)

        # Test masking on encrypted config (what DB returns)
        masked_from_enc = mask_connector_config(enc_config)
        m_creds = masked_from_enc["credentials"]
        self.assertEqual(m_creds["zendesk_subdomain"], "mycompany")
        self.assertEqual(m_creds["zendesk_email"], "agent@mycompany.com")
        self.assertEqual(m_creds["zendesk_token"], "********")
        self.assertEqual(m_creds["some_obscure_secret"], "********")

        # Also test masking on plaintext config
        masked_from_plain = mask_connector_config(raw_config)
        self.assertEqual(masked_from_plain["credentials"]["zendesk_token"], "********")
        self.assertEqual(masked_from_plain["credentials"]["some_obscure_secret"], "********")

    # -------------------------------------------------------------------------
    # 9. Safe Update / Merge Pattern (Preserves Existing Secrets)
    # -------------------------------------------------------------------------
    def test_merge_updated_connector_config(self):
        stored_raw_config = {
            "source": "bitbucket",
            "credentials": {
                "username": "bb_admin",
                "app_password": "real_secret_password_12345",
                "account_id": "acc-9988",
            },
            "refresh_freq": 5
        }
        stored_enc_config = encrypt_connector_config(stored_raw_config)
        original_enc_password = stored_enc_config["credentials"]["app_password"]
        self.assertTrue(original_enc_password.startswith("enc:v2:"))

        # Scenario A: UI sends "********" mask placeholder
        incoming_ui_payload = {
            "credentials": {
                "username": "bb_admin",
                "app_password": "********",
                "account_id": "acc-9988",
            },
            "refresh_freq": 15
        }
        merged = merge_updated_connector_config(stored_enc_config, incoming_ui_payload)
        self.assertEqual(merged["refresh_freq"], 15)
        self.assertEqual(merged["credentials"]["app_password"], original_enc_password)

        decrypted_merged = decrypt_connector_config(merged)
        self.assertEqual(decrypted_merged["credentials"]["app_password"], "real_secret_password_12345")

        # Scenario B: User provides a real new password
        incoming_new_pw_payload = {
            "credentials": {
                "username": "bb_admin",
                "app_password": "brand_new_password_99999",
                "account_id": "acc-9988",
            },
            "refresh_freq": 15
        }
        merged_new_pw = merge_updated_connector_config(stored_enc_config, incoming_new_pw_payload)
        new_enc_password = merged_new_pw["credentials"]["app_password"]
        self.assertTrue(new_enc_password.startswith("enc:v2:"))
        self.assertNotEqual(new_enc_password, original_enc_password)

        decrypted_new = decrypt_connector_config(merged_new_pw)
        self.assertEqual(decrypted_new["credentials"]["app_password"], "brand_new_password_99999")

        # Scenario C: UI sends empty string for existing secret
        incoming_empty_pw = {
            "credentials": {
                "username": "bb_admin",
                "app_password": "",
                "account_id": "acc-9988",
            }
        }
        merged_empty = merge_updated_connector_config(stored_enc_config, incoming_empty_pw)
        self.assertEqual(merged_empty["credentials"]["app_password"], original_enc_password)

    # -------------------------------------------------------------------------
    # 10. Syncer Decryption and OAuth Token Refresh Re-encryption
    # -------------------------------------------------------------------------
    def test_syncer_decryption_and_oauth_refresh(self):
        stored_config = {
            "source": "gmail",
            "credentials": {
                "client_id": "gmail_client_id_123.apps.googleusercontent.com",
                "client_secret": "gmail_secret_456",
                "refresh_token": "original_refresh_token_789",
                "access_token": "expired_access_token_000",
            }
        }
        db_config = encrypt_connector_config(stored_config)
        self.assertTrue(db_config["credentials"]["client_secret"].startswith("enc:v2:"))
        self.assertTrue(db_config["credentials"]["refresh_token"].startswith("enc:v2:"))
        self.assertTrue(db_config["credentials"]["access_token"].startswith("enc:v2:"))

        # 1. Syncer starts: decrypts config to connect to Google API
        syncer_config = decrypt_connector_config(db_config)
        self.assertEqual(syncer_config["credentials"]["client_secret"], "gmail_secret_456")
        self.assertEqual(syncer_config["credentials"]["refresh_token"], "original_refresh_token_789")

        # 2. Syncer receives new OAuth access token from Google OAuth endpoint:
        refreshed_access_token = "brand_new_refreshed_access_token_from_google_api_999"
        update_payload = {
            "credentials": {
                "access_token": refreshed_access_token,
            }
        }

        # 3. Syncer writes back to DB via merge_updated_connector_config:
        updated_db_config = merge_updated_connector_config(db_config, update_payload)

        new_enc_token = updated_db_config["credentials"]["access_token"]
        self.assertTrue(new_enc_token.startswith("enc:v2:"), f"Refreshed token was saved as plaintext! Got: {new_enc_token}")
        self.assertNotEqual(new_enc_token, refreshed_access_token)

        recovered = decrypt_connector_config(updated_db_config)
        self.assertEqual(recovered["credentials"]["access_token"], refreshed_access_token)

    # -------------------------------------------------------------------------
    # 11. Migration CLI: Find Unencrypted, Rollback Reverse, Key Rotation
    # -------------------------------------------------------------------------
    def test_migration_cli_helpers(self):
        plaintext_cfg = {
            "credentials": {
                "instance_url": "https://example.com",
                "jira_api_token": "raw_token_xyz",
                "nested_auth": {
                    "private_key": "raw_key_abc",
                    "public_field": "visible"
                }
            }
        }
        # 1. Plaintext config has 2 unencrypted fields
        unenc = find_unencrypted_keys(plaintext_cfg)
        self.assertIn("credentials.jira_api_token", unenc)
        self.assertIn("credentials.nested_auth.private_key", unenc)
        self.assertNotIn("credentials.instance_url", unenc)

        # 2. Encrypted config has 0 unencrypted fields
        enc_cfg = encrypt_connector_config(plaintext_cfg)
        self.assertEqual(len(find_unencrypted_keys(enc_cfg)), 0)

        # 3. Encrypted config has 2 encrypted fields
        enc_fields = find_encrypted_keys(enc_cfg)
        self.assertIn("credentials.jira_api_token", enc_fields)
        self.assertIn("credentials.nested_auth.private_key", enc_fields)

        # 4. Reverse rollback restores exact plaintext
        reversed_cfg = decrypt_connector_config(enc_cfg)
        self.assertEqual(reversed_cfg, plaintext_cfg)
        self.assertEqual(len(find_encrypted_keys(reversed_cfg)), 0)

    # -------------------------------------------------------------------------
    # 12. Real Connector Blueprint: HTTP Leak Regression via connector_api.py
    # -------------------------------------------------------------------------
    # -------------------------------------------------------------------------
    # 12. Helper & Blueprint Mutation Tests (List, Create, Update)
    # -------------------------------------------------------------------------
    def _setup_real_connector_blueprint(self):
        import importlib.util
        import sys
        import types
        from quart import Blueprint, Quart

        raw_api_key = "super_confidential_crm_bearer_token_xyz_999"
        raw_client_secret = "raw_oauth_client_secret_abc_456"
        raw_http_pass = "http_pass_777"
        raw_db_config = {
            "credentials": {
                "instance_url": f"https://admin:{raw_http_pass}@crm.corp.internal",
                "client_id": "public_cid_123",
                "client_secret": raw_client_secret,
            },
            "auth_config": {
                "api_key": raw_api_key,
            },
            "headers": {
                "Authorization": f"Bearer {raw_api_key}",
            },
        }
        stored_enc_config = encrypt_connector_config(raw_db_config)

        import api.utils.key_crypto as _real_key_crypto

        _records = {}

        class _FakeConn:
            def __init__(self, cfg=None, name="Production Salesforce CRM"):
                self.config = cfg if cfg is not None else stored_enc_config
                self.name = name

            def to_dict(self):
                return {
                    "id": "conn-fake-001",
                    "tenant_id": "tenant-123",
                    "name": self.name,
                    "source": "salesforce",
                    "config": self.config,
                }

        class _FakeConnectorService:
            @staticmethod
            def accessible(connector_id, user_id):
                return True

            @classmethod
            def get_by_id(cls, connector_id):
                conn = _records.get(connector_id, _FakeConn())
                return True, conn

            @classmethod
            def list(cls, tenant_id):
                return [{"id": "conn-fake-001", "name": "Production Salesforce CRM", "source": "salesforce", "status": "UNSTART"}]

            @classmethod
            def save(cls, **kwargs):
                _records[kwargs["id"]] = _FakeConn(cfg=kwargs.get("config"), name=kwargs.get("name", ""))
                return True

            @classmethod
            def update_by_id(cls, connector_id, update_fields):
                existing = _records.get(connector_id, _FakeConn())
                new_cfg = update_fields.get("config", existing.config)
                _records[connector_id] = _FakeConn(cfg=new_cfg, name=existing.name)
                return True

        class _FakeSyncLogsService:
            @staticmethod
            def list_sync_tasks(connector_id, page, page_size):
                return [], 0

        from common.constants import RetCode as _RealRetCode
        from quart import jsonify as _jsonify

        def _fake_get_json_result(data=None, message="success", code=0):
            return _jsonify({"code": code, "message": message, "data": data})

        def _fake_get_data_error_result(code=102, message="Data error"):
            return _jsonify({"code": code, "message": message, "data": False})

        from functools import wraps as _wraps

        def _fake_login_required(func=None, auth_types=None):
            def decorator(f):
                @_wraps(f)
                async def wrapper(*args, **kwargs):
                    if asyncio.iscoroutinefunction(f):
                        return await f(*args, **kwargs)
                    return f(*args, **kwargs)
                return wrapper
            if func is None:
                return decorator
            return decorator(func)

        class _FakeCurrentUser:
            id = "user-test-001"

        def _make_dummy(name, **attrs):
            m = types.ModuleType(name)
            m.__dict__.update(attrs)
            return m

        async def _fake_get_request_json():
            from quart import request
            return await request.get_json() or {}

        stubs = {
            "google_auth_oauthlib": _make_dummy("google_auth_oauthlib"),
            "google_auth_oauthlib.flow": _make_dummy("google_auth_oauthlib.flow", Flow=None),
            "box_sdk_gen": _make_dummy("box_sdk_gen",
                BoxOAuth=None, OAuthConfig=None, GetAuthorizeUrlOptions=None),
            "rag": _make_dummy("rag"),
            "rag.utils": _make_dummy("rag.utils"),
            "rag.utils.redis_conn": _make_dummy("rag.utils.redis_conn", REDIS_CONN=None),
            "common.data_source": _make_dummy("common.data_source"),
            "common.data_source.config": _make_dummy(
                "common.data_source.config",
                GOOGLE_DRIVE_WEB_OAUTH_REDIRECT_URI="",
                GMAIL_WEB_OAUTH_REDIRECT_URI="",
                BOX_WEB_OAUTH_REDIRECT_URI="",
                DocumentSource=None,
            ),
            "common.data_source.google_util": _make_dummy("common.data_source.google_util"),
            "common.data_source.google_util.constant": _make_dummy(
                "common.data_source.google_util.constant",
                WEB_OAUTH_POPUP_TEMPLATE="",
                GOOGLE_SCOPES=[],
            ),
            "common.misc_utils": _make_dummy("common.misc_utils",
                get_uuid=lambda: "fake-uuid-1234"),
            "api.db": _make_dummy("api.db",
                InputType=type("InputType", (), {"POLL": "poll"})),
            "api.db.services.connector_service": _make_dummy(
                "api.db.services.connector_service",
                ConnectorService=_FakeConnectorService,
                SyncLogsService=_FakeSyncLogsService,
                ConnectorAuthorizationError=Exception,
            ),
            "api.utils.api_utils": _make_dummy(
                "api.utils.api_utils",
                get_json_result=_fake_get_json_result,
                get_data_error_result=_fake_get_data_error_result,
                get_request_json=_fake_get_request_json,
                validate_request=lambda *a, **kw: (lambda f: f),
            ),
            "api.utils.pagination_utils": _make_dummy(
                "api.utils.pagination_utils",
                DEFAULT_PAGE=1, DEFAULT_PAGE_SIZE=20,
                validate_rest_api_page=lambda x: int(x),
                validate_rest_api_page_size=lambda x: int(x),
            ),
            "common.constants": _make_dummy(
                "common.constants",
                FileSource=None,
                RetCode=_RealRetCode,
                TaskStatus=type("TaskStatus", (), {
                    "CANCEL": "CANCEL", "SCHEDULE": "SCHEDULE", "UNSTART": "UNSTART"}),
            ),
            "api.utils.key_crypto": _real_key_crypto,
            "api.apps": _make_dummy(
                "api.apps",
                login_required=_fake_login_required,
                current_user=_FakeCurrentUser(),
            ),
        }

        saved = {}
        for k, v in stubs.items():
            saved[k] = sys.modules.get(k)
            sys.modules[k] = v

        connector_api_path = os.path.abspath(os.path.join(
            os.path.dirname(__file__), "..", "api", "apps", "restful_apis", "connector_api.py"
        ))

        try:
            mod_name = "api.apps.restful_apis.connector_api"
            spec = importlib.util.spec_from_file_location(mod_name, connector_api_path)
            mod = importlib.util.module_from_spec(spec)
            mod.manager = Blueprint("connector_api", mod_name)
            sys.modules[mod_name] = mod
            spec.loader.exec_module(mod)
            _orig_sleep = asyncio.sleep
            mod.asyncio.sleep = lambda s: _orig_sleep(0)
        finally:
            for k, orig in saved.items():
                if orig is None:
                    sys.modules.pop(k, None)
                else:
                    sys.modules[k] = orig
            sys.modules.pop("api.apps.restful_apis.connector_api", None)

        test_app = Quart("test_real_blueprint")
        test_app.config["TESTING"] = True
        test_app.config["SECRET_KEY"] = "test-secret"
        test_app.register_blueprint(mod.manager, url_prefix="/api/v1")

        return test_app, mod, raw_db_config, raw_api_key, raw_client_secret, raw_http_pass, _real_key_crypto, _records, _FakeConnectorService

    def test_connector_blueprint_list_masking_mutation(self):
        """Python Blueprint list mutation test: list endpoint must never project or leak credentials."""
        test_app, mod, raw_db_config, raw_api_key, raw_client_secret, raw_http_pass, _real_key_crypto, _records, fake_svc = self._setup_real_connector_blueprint()

        async def _run_list():
            async with test_app.test_client() as client:
                resp = await client.get("/api/v1/connectors")
                self.assertEqual(resp.status_code, 200)
                body = await resp.get_data(as_text=True)
                self.assertNotIn(raw_api_key, body)
                self.assertNotIn(raw_client_secret, body)
                self.assertNotIn(raw_http_pass, body)
                self.assertNotIn("credentials", body)

        # 1. Clean run: passes
        asyncio.run(_run_list())

        # 2. Mutation: inject unmasked credentials into list projection
        orig_list = fake_svc.list
        fake_svc.list = lambda tid: [{"id": "c1", "name": "Leaker", "config": raw_db_config}]
        mutation_caught = False
        try:
            asyncio.run(_run_list())
        except AssertionError as exc:
            mutation_caught = True
            print(f"\n[MUTATION OK] list projected credentials -> caught by assertion: {exc}")
        finally:
            fake_svc.list = orig_list

        self.assertTrue(mutation_caught, "List mutation was not caught!")

    def test_connector_blueprint_create_masking_mutation(self):
        """Python Blueprint POST create mutation test: response must mask all secrets."""
        test_app, mod, raw_db_config, raw_api_key, raw_client_secret, raw_http_pass, _real_key_crypto, _records, fake_svc = self._setup_real_connector_blueprint()

        async def _run_create():
            async with test_app.test_client() as client:
                resp = await client.post("/api/v1/connectors", json={
                    "name": "New Salesforce",
                    "source": "salesforce",
                    "config": raw_db_config,
                })
                self.assertEqual(resp.status_code, 200)
                body = await resp.get_data(as_text=True)
                self.assertNotIn(raw_api_key, body)
                self.assertNotIn(raw_client_secret, body)
                self.assertNotIn(raw_http_pass, body)

                import json as _json
                cfg = _json.loads(body)["data"]["config"]
                self.assertEqual(cfg["credentials"]["client_secret"], "********")
                self.assertEqual(cfg["auth_config"]["api_key"], "********")

        # 1. Clean run: passes
        asyncio.run(_run_create())

        # 2. Mutation: bypass mask_connector_config in response
        _orig_mod_mask = getattr(mod, "mask_connector_config", None)
        _orig_crypto_mask = _real_key_crypto.mask_connector_config
        mod.mask_connector_config = lambda cfg, *a, **kw: cfg
        _real_key_crypto.mask_connector_config = lambda cfg, *a, **kw: cfg
        mutation_caught = False
        try:
            asyncio.run(_run_create())
        except AssertionError as exc:
            mutation_caught = True
            print(f"\n[MUTATION OK] POST create masking bypassed -> caught by assertion: {exc}")
        finally:
            if _orig_mod_mask:
                mod.mask_connector_config = _orig_mod_mask
            _real_key_crypto.mask_connector_config = _orig_crypto_mask

        self.assertTrue(mutation_caught, "POST create mutation was not caught!")

    def test_connector_blueprint_update_masking_mutation(self):
        """Python Blueprint PATCH update mutation test: response must mask all secrets."""
        test_app, mod, raw_db_config, raw_api_key, raw_client_secret, raw_http_pass, _real_key_crypto, _records, fake_svc = self._setup_real_connector_blueprint()

        async def _run_update():
            async with test_app.test_client() as client:
                resp = await client.patch("/api/v1/connectors/conn-fake-001", json={
                    "config": {
                        "credentials": {
                            "client_secret": raw_client_secret,
                        }
                    }
                })
                self.assertEqual(resp.status_code, 200)
                body = await resp.get_data(as_text=True)
                self.assertNotIn(raw_api_key, body)
                self.assertNotIn(raw_client_secret, body)
                self.assertNotIn(raw_http_pass, body)

                import json as _json
                cfg = _json.loads(body)["data"]["config"]
                self.assertEqual(cfg["credentials"]["client_secret"], "********")

        # 1. Clean run: passes
        asyncio.run(_run_update())

        # 2. Mutation: bypass mask_connector_config in response
        _orig_mod_mask = getattr(mod, "mask_connector_config", None)
        _orig_crypto_mask = _real_key_crypto.mask_connector_config
        mod.mask_connector_config = lambda cfg, *a, **kw: cfg
        _real_key_crypto.mask_connector_config = lambda cfg, *a, **kw: cfg
        mutation_caught = False
        try:
            asyncio.run(_run_update())
        except AssertionError as exc:
            mutation_caught = True
            print(f"\n[MUTATION OK] PATCH update masking bypassed -> caught by assertion: {exc}")
        finally:
            if _orig_mod_mask:
                mod.mask_connector_config = _orig_mod_mask
            _real_key_crypto.mask_connector_config = _orig_crypto_mask

        self.assertTrue(mutation_caught, "PATCH update mutation was not caught!")

    def test_real_connector_blueprint_leak_regression(self):
        """Comprehensive regression test running GET by ID, GET list, POST create, PATCH update."""
        test_app, mod, raw_db_config, raw_api_key, raw_client_secret, raw_http_pass, _real_key_crypto, _records, fake_svc = self._setup_real_connector_blueprint()

        async def _assert_no_leaks():
            async with test_app.test_client() as client:
                # 1. GET by id
                resp = await client.get("/api/v1/connectors/conn-fake-001")
                self.assertEqual(resp.status_code, 200)
                body = await resp.get_data(as_text=True)
                self.assertNotIn(raw_api_key, body)
                self.assertNotIn(raw_client_secret, body)
                self.assertNotIn(raw_http_pass, body)

                # 2. GET list
                resp_list = await client.get("/api/v1/connectors")
                self.assertEqual(resp_list.status_code, 200)
                body_list = await resp_list.get_data(as_text=True)
                self.assertNotIn(raw_api_key, body_list)
                self.assertNotIn(raw_client_secret, body_list)
                self.assertNotIn(raw_http_pass, body_list)

                # 3. POST create
                resp_post = await client.post("/api/v1/connectors", json={
                    "name": "New Salesforce",
                    "source": "salesforce",
                    "config": raw_db_config,
                })
                self.assertEqual(resp_post.status_code, 200)
                body_post = await resp_post.get_data(as_text=True)
                self.assertNotIn(raw_api_key, body_post)
                self.assertNotIn(raw_client_secret, body_post)
                self.assertNotIn(raw_http_pass, body_post)

                # 4. PATCH update
                resp_patch = await client.patch("/api/v1/connectors/conn-fake-001", json={
                    "config": {
                        "credentials": {
                            "client_secret": raw_client_secret,
                        }
                    }
                })
                self.assertEqual(resp_patch.status_code, 200)
                body_patch = await resp_patch.get_data(as_text=True)
                self.assertNotIn(raw_api_key, body_patch)
                self.assertNotIn(raw_client_secret, body_patch)
                self.assertNotIn(raw_http_pass, body_patch)

        asyncio.run(_assert_no_leaks())

    # -------------------------------------------------------------------------
    # 13. Real Syncer dispatch_tasks() Decryption & Mutation Test
    # -------------------------------------------------------------------------
    def test_real_dispatch_tasks_decryption_mutation(self):
        """
        Invoke the REAL dispatch_tasks() from rag/svr/sync_data_source.py.
        Prove that it calls decrypt_connector_config() so worker factories receive
        plaintext secrets, and prove mutation: removing decrypt causes assertion failure.
        """
        import types
        import importlib.util

        class AutoMock(types.ModuleType):
            def __init__(self, name):
                super().__init__(name)
                self.__path__ = []
            def __getattr__(self, name):
                val = AutoMock(f"{self.__name__}.{name}")
                setattr(self, name, val)
                return val
            def __call__(self, *args, **kwargs): return AutoMock("call")

        saved_mods = {}
        for m in [
            "common.data_source", "box_sdk_gen", "common.data_source.models",
            "common.data_source.webdav_connector", "common.data_source.confluence_connector",
            "common.data_source.gmail_connector", "common.data_source.box_connector",
            "common.data_source.github.connector", "common.data_source.gitlab_connector",
            "common.data_source.bitbucket.connector", "common.data_source.azure_devops.connector",
            "common.data_source.interfaces", "common.data_source.sitemap_connector",
            "common.data_source.exceptions", "common.data_source.config", "common.log_utils",
            "common.signal_utils"
        ]:
            saved_mods[m] = sys.modules.get(m)
            sys.modules[m] = AutoMock(m)

        sds_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "rag", "svr", "sync_data_source.py"))
        try:
            spec = importlib.util.spec_from_file_location("rag.svr.sync_data_source", sds_path)
            mod = importlib.util.module_from_spec(spec)
            sys.modules["rag.svr.sync_data_source"] = mod
            spec.loader.exec_module(mod)
        finally:
            for m, orig in saved_mods.items():
                if orig is None:
                    sys.modules.pop(m, None)
                else:
                    sys.modules[m] = orig

        raw_token = "super-secret-sync-token-12345"
        enc_cfg = encrypt_connector_config({
            "credentials": {
                "jira_api_token": raw_token,
                "instance_url": "https://jira.corp",
            }
        })

        captured_conf = {}
        async def fake_runner(task): pass
        def fake_factory(conf):
            captured_conf.clear()
            captured_conf.update(conf)
            return fake_runner

        mod.func_factory = {"jira": fake_factory}
        mod.SyncLogsService.list_due_sync_tasks = lambda: [{
            "id": "t1", "source": "jira", "config": enc_cfg, "poll_range_start": None, "poll_range_end": None
        }]
        mod.SyncLogsService.list_due_prune_tasks = lambda: []
        _orig_sleep = asyncio.sleep
        mod.asyncio.sleep = lambda s: _orig_sleep(0)

        # 1. Clean run: dispatch_tasks() decrypts before passing to factory
        asyncio.run(mod.dispatch_tasks())
        self.assertEqual(
            captured_conf["credentials"]["jira_api_token"],
            raw_token,
            "Real dispatch_tasks() did not decrypt credentials for connector worker!"
        )

        # 2. MUTATION VERIFICATION: bypass decrypt_connector_config -> MUST FAIL
        _orig_decrypt = mod.decrypt_connector_config
        mod.decrypt_connector_config = lambda cfg: cfg  # identity bypass (mutation)
        mutation_caught = False
        try:
            asyncio.run(mod.dispatch_tasks())
            self.assertEqual(captured_conf["credentials"]["jira_api_token"], raw_token)
        except AssertionError as exc:
            mutation_caught = True
            print(f"\n[MUTATION OK] dispatch_tasks decrypt removed -> caught by assertion:\n  {exc}")
        finally:
            mod.decrypt_connector_config = _orig_decrypt

        self.assertTrue(mutation_caught, "MUTATION GUARD FAILED: bypassing decrypt_connector_config in dispatch_tasks was not caught!")

    # -------------------------------------------------------------------------
    # 14. Real Worker OAuth Refresh Persists enc:v2: to Database
    # -------------------------------------------------------------------------
    def test_real_worker_oauth_refresh_persists_enc_v2_to_db(self):
        """
        Execute the REAL ConnectorService.update_by_id() path invoked by workers
        (rag/svr/sync_data_source.py:803/954/1751) on a real SQLite-backed Connector table.
        Prove that:
        1. Refreshed token is persisted as enc:v2: in the DB column.
        2. Plaintext token NEVER appears in the database row.
        3. ConnectorService.get_decrypted_config() recovers the plaintext token.
        4. Mutation: bypassing merge_updated_connector_config leaks plaintext to DB and fails.
        """
        from unittest.mock import patch
        from peewee import SqliteDatabase
        from api.db.db_models import DB, Connector
        from api.db.services.connector_service import ConnectorService

        class _DummyCtx:
            def __enter__(self):
                return self
            def __exit__(self, *args):
                pass
            def __call__(self, fn):
                return fn

        test_db = SqliteDatabase(":memory:")
        _orig_connect = DB.connect
        _orig_close = DB.close
        _orig_is_closed = DB.is_closed

        DB.connect = lambda *a, **kw: True
        DB.close = lambda *a, **kw: None
        DB.is_closed = lambda: False

        _orig_db = Connector._meta.database
        try:
            Connector._meta.database = test_db
            test_db.bind([Connector])
            test_db.connect()
            test_db.create_tables([Connector])

            # Initial connector record
            initial_cfg = {"credentials": {"access_token": "old-token-000", "client_id": "cid-123"}}
            enc_init = encrypt_connector_config(initial_cfg)
            Connector.create(
                id="conn-worker-001",
                tenant_id="tenant-worker",
                name="Worker OAuth Connector",
                source="salesforce",
                input_type="poll",
                config=enc_init,
            )

            # Worker refreshes oauth token via ConnectorService.update_by_id
            refreshed_token = "brand-new-refreshed-oauth-token-999"
            update_payload = {"credentials": {"access_token": refreshed_token}}
            ConnectorService.update_by_id("conn-worker-001", {"config": update_payload})

            # 1. Read directly from DB
            row = Connector.get_by_id("conn-worker-001")
            token_in_db = row.config["credentials"]["access_token"]
            self.assertTrue(
                token_in_db.startswith("enc:v2:"),
                f"Token was stored plaintext in DB! Got: {token_in_db}"
            )
            self.assertNotIn(
                refreshed_token,
                str(row.config),
                "Raw token leaked into DB row JSON!"
            )

            # 2. Service decrypts properly
            decrypted = ConnectorService.get_decrypted_config("conn-worker-001")
            self.assertEqual(decrypted["credentials"]["access_token"], refreshed_token)

            # 3. MUTATION VERIFICATION: bypass merge_updated_connector_config in update_by_id
            import api.db.services.connector_service as cs_mod
            _orig_merge = cs_mod.merge_updated_connector_config
            cs_mod.merge_updated_connector_config = lambda exist, upd: upd  # mutation: raw update
            mutation_caught = False
            try:
                ConnectorService.update_by_id("conn-worker-001", {"config": {"credentials": {"access_token": "leaked-token"}}})
                mutated_row = Connector.get_by_id("conn-worker-001")
                mutated_token = mutated_row.config["credentials"]["access_token"]
                self.assertTrue(mutated_token.startswith("enc:v2:"), "MUTATION TRIGGER: raw token written to DB!")
            except AssertionError as exc:
                mutation_caught = True
                print(f"\n[MUTATION OK] update_by_id merge bypassed -> caught by assertion:\n  {exc}")
            finally:
                cs_mod.merge_updated_connector_config = _orig_merge

            self.assertTrue(mutation_caught, "MUTATION GUARD FAILED: bypassing merge in update_by_id was not caught!")

        finally:
            Connector._meta.database = _orig_db
            DB.connect = _orig_connect
            DB.close = _orig_close
            DB.is_closed = _orig_is_closed
            if not test_db.is_closed():
                test_db.close()

    def test_database_isolation_guarantee(self):
        """Verify tests run against in-memory SQLite and cannot touch real MySQL settings.DATABASE."""
        from unittest.mock import patch
        from peewee import SqliteDatabase
        from api.db.db_models import DB, Connector

        test_db = SqliteDatabase(":memory:")
        _orig_db = Connector._meta.database
        _orig_atomic = getattr(DB, "atomic", None)
        try:
            Connector._meta.database = test_db
            DB.atomic = lambda *args, **kwargs: test_db.atomic()
            test_db.bind([Connector])
            test_db.connect()
            test_db.create_tables([Connector])

            with patch.object(DB, "connect", side_effect=RuntimeError("Direct MySQL access forbidden!")):
                Connector.create(
                    id="conn-iso-test",
                    tenant_id="tenant-iso",
                    name="Isolated Connector",
                    source="salesforce",
                    input_type="poll",
                    config={"credentials": {"access_token": "secret"}},
                )
                res = list(Connector.select().where(Connector.id == "conn-iso-test"))
                self.assertEqual(len(res), 1)
        finally:
            Connector._meta.database = _orig_db
            if _orig_atomic:
                DB.atomic = _orig_atomic
            if not test_db.is_closed():
                test_db.close()



    # -------------------------------------------------------------------------
    # 13. URL Round-Trip PATCH: masked URL must preserve original secret
    # -------------------------------------------------------------------------
    def test_url_roundtrip_patch_masked_url(self):
        """
        PATCH contract: if the UI sends back a masked URL
        (https://user:********@host?token=********) the stored original
        secret must be preserved — no data is lost or corrupted.
        """
        original_url = (
            "https://service-user:p@ssw0rd!Really$ecret"
            "@jira.corp.local/api?token=s3cr3t-tok3n"
        )
        original_password = "p@ssw0rd!Really$ecret"
        original_token = "s3cr3t-tok3n"

        raw_config = {
            "credentials": {
                "instance_url": original_url,
                "client_id": "public-client-id",
            }
        }
        stored_enc = encrypt_connector_config(raw_config)

        # Mask as returned to UI
        masked = mask_connector_config(stored_enc)
        masked_url = masked["credentials"]["instance_url"]

        # Confirm masking worked
        self.assertNotIn(original_password, masked_url,
            "Password not masked in instance_url")
        self.assertNotIn(original_token, masked_url,
            "Token not masked in instance_url")
        self.assertIn("********", masked_url)

        # UI sends back the masked URL unchanged in PATCH body
        patch_payload = {
            "credentials": {
                "instance_url": masked_url,
                "client_id": "public-client-id",
            }
        }

        merged = merge_updated_connector_config(stored_enc, patch_payload)

        # After merge, value must still be encrypted (not the bare masked sentinel)
        merged_url_val = merged["credentials"]["instance_url"]
        self.assertTrue(
            merged_url_val.startswith("enc:v2:"),
            f"Expected enc:v2: after PATCH with masked URL, got: {merged_url_val!r}"
        )

        # Decrypting must recover the ORIGINAL full URL
        recovered = decrypt_connector_config(merged)
        self.assertEqual(
            recovered["credentials"]["instance_url"],
            original_url,
            f"URL round-trip FAILED — original secret was lost!\n"
            f"  original : {original_url!r}\n"
            f"  recovered: {recovered['credentials']['instance_url']!r}"
        )

    # -------------------------------------------------------------------------
    # 14. AI Provider Radius of Impact: Legacy enc:v1: Decryption & Key Rotation
    # -------------------------------------------------------------------------
    def test_ai_provider_legacy_v1_and_rotation_behavior(self):
        """
        ai_provider_service uses key_crypto.py for LLM API keys.
        Existing keys in production were encrypted under legacy enc:v1: (HMAC-SHA256 CTR).
        This test proves:
        1. An existing enc:v1: key decrypts properly with the original secret.
        2. When rotated to a new primary secret (with old key in RAGFLOW_SECRET_KEYS_ROTATION),
           the enc:v1: key continues to decrypt seamlessly.
        3. When a new key is encrypted, it automatically gets modern enc:v2: (AES-256-GCM).
        4. If secret changes without old key in rotation list, decryption fails safely
           without crashing, returning the ciphertext and logging an error.
        """
        old_ai_secret = "legacy-ai-provider-secret-key-32b!"
        raw_openai_key = "sk-proj-super-confidential-openai-api-key-12345"

        # Known enc:v1: vector generated with old_ai_secret
        # iv: 16 bytes "0123456789abcdef", payload encrypted with HMAC-CTR using old_ai_secret
        # We can construct or verify via decrypt_api_key
        legacy_v1_vector = "enc:v1:MDEyMzQ1Njc4OWFiY2RlZi2J+E1szJ+OKGOCVomikPPcq0j8d0Yjn7GmJSVm2UwuvGA+XSQUssnHfH0HcjdVGcLw"
        expected_plain = "cross-lang-test-secret-value-12345"

        # 1. Decrypt with matching master secret (self.master_secret)
        decrypted_primary = decrypt_api_key(legacy_v1_vector, self.master_secret)
        self.assertEqual(decrypted_primary, expected_plain, "Failed to decrypt legacy v1 with primary key")

        # 2. Key rotation: master secret changes to new_secret, old key moved to rotation list
        new_secret = "brand-new-primary-key-32bytes-ok!"
        os.environ["RAGFLOW_SECRET_KEY"] = new_secret
        os.environ["RAGFLOW_SECRET_KEYS_ROTATION"] = f"unrelated-key,{self.master_secret}"

        # decrypt_api_key with no explicit secret should use keyring and succeed
        decrypted_rotated = decrypt_api_key(legacy_v1_vector)
        self.assertEqual(decrypted_rotated, expected_plain, "Failed to decrypt legacy v1 via rotation keyring")

        # 3. New encryption under new primary key produces enc:v2:
        new_enc = encrypt_api_key("sk-proj-new-key-12345")
        self.assertTrue(new_enc.startswith("enc:v2:"), f"Expected enc:v2:, got: {new_enc}")
        self.assertEqual(decrypt_api_key(new_enc), "sk-proj-new-key-12345")

        # 4. Unknown key: neither primary nor rotation matches -> fails safely, returns ciphertext
        os.environ["RAGFLOW_SECRET_KEY"] = "completely-different-key-32bytes!!"
        os.environ.pop("RAGFLOW_SECRET_KEYS_ROTATION", None)
        failed_dec = decrypt_api_key(legacy_v1_vector)
        self.assertEqual(failed_dec, legacy_v1_vector, "Unknown key should safely return ciphertext without crash")

    # -------------------------------------------------------------------------
    # 15. Keyring Decrypt-Only for Insecure Defaults (Historical Data Migration)
    # -------------------------------------------------------------------------
    def test_keyring_decrypt_only_insecure_default_secret(self):
        """
        Prove that RAGFLOW_SECRET_KEYS_ROTATION accepts INSECURE_DEFAULT_KEYS for decrypt-only.
        Data previously encrypted under 'ragflow_single_global_instance_master_secret_2026'
        successfully decrypts, while encryption with that key remains strictly forbidden (fail-closed).
        """
        import base64
        import hashlib
        import hmac
        from api.utils.key_crypto import _derive_legacy_v1_keys, _legacy_v1_keystream

        default_sec = "ragflow_single_global_instance_master_secret_2026"
        plain_secret = "legacy-ai-secret-encrypted-with-hardcoded-default-2026"

        # 1. Synthesize enc:v1 ciphertext using legacy cipher and default_sec
        k_enc, k_mac = _derive_legacy_v1_keys(default_sec)
        iv = b"0123456789abcdef"
        data = plain_secret.encode("utf-8")
        ks = _legacy_v1_keystream(k_enc, iv, len(data))
        ct = bytes(a ^ b for a, b in zip(data, ks))
        tag = hmac.new(k_mac, iv + ct, hashlib.sha256).digest()[:16]
        legacy_v1 = "enc:v1:" + base64.b64encode(iv + tag + ct).decode("ascii")

        # 2. Configure primary secure key, and put default_sec in RAGFLOW_SECRET_KEYS_ROTATION
        os.environ["RAGFLOW_SECRET_KEY"] = self.master_secret
        os.environ["RAGFLOW_SECRET_KEYS_ROTATION"] = f"some-key-1,{default_sec},some-key-2"

        # Decrypt succeeds via keyring
        decrypted = decrypt_api_key(legacy_v1)
        self.assertEqual(decrypted, plain_secret, "Failed to decrypt legacy v1 with default key via rotation keyring")

        # 3. Encrypt with default_sec is strictly forbidden (fail-closed)
        with self.assertRaises(InsecureSecretKeyError):
            encrypt_api_key("test-secret", secret=default_sec)

        # Also when default_sec is set as primary RAGFLOW_SECRET_KEY, encrypt must fail
        os.environ["RAGFLOW_SECRET_KEY"] = default_sec
        with self.assertRaises(InsecureSecretKeyError):
            encrypt_api_key("test-secret")


if __name__ == "__main__":
    unittest.main()


