#
#  Copyright 2026 The InfiniFlow Authors. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import asyncio
import os
import sys
import unittest
from quart import Quart, jsonify, request

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from api.utils.key_crypto import (
    encrypt_api_key,
    decrypt_api_key,
    encrypt_connector_config,
    decrypt_connector_config,
    mask_connector_config,
    merge_updated_connector_config,
    is_masked_value,
    is_encrypted_key,
    has_embedded_url_credentials,
    sanitize_url_credentials,
    validate_master_secret,
    InsecureSecretKeyError,
    PUBLIC_IDENTIFIER_FIELDS,
)
from api.scripts.migrate_connector_credentials import (
    find_unencrypted_keys,
    find_encrypted_keys,
)


class TestConnectorSecurity(unittest.TestCase):
    def setUp(self):
        self.master_secret = "test-master-secret-key-32bytes-ok!"
        os.environ["RAGFLOW_SECRET_KEY"] = self.master_secret

    def tearDown(self):
        os.environ.pop("RAGFLOW_SECRET_KEY", None)
        os.environ.pop("RAGFLOW_SECRET_KEYS_ROTATION", None)

    # -------------------------------------------------------------------------
    # 1. Primitives: AES-256-GCM (enc:v2:) and Tamper Resistance
    # -------------------------------------------------------------------------
    def test_crypto_primitives_aes256_gcm(self):
        plaintext = "super_secret_crm_api_key_12345"

        enc = encrypt_api_key(plaintext, self.master_secret)
        self.assertTrue(enc.startswith("enc:v2:"), f"Expected enc:v2: prefix, got {enc}")

        # Idempotency
        enc2 = encrypt_api_key(enc, self.master_secret)
        self.assertEqual(enc, enc2)

        # Decryption
        dec = decrypt_api_key(enc, self.master_secret)
        self.assertEqual(dec, plaintext)

        # Empty string handling
        self.assertEqual(encrypt_api_key("", self.master_secret), "")
        self.assertEqual(decrypt_api_key("", self.master_secret), "")

        # Tamper resistance: corrupted ciphertext tag must not raise uncaught exception, but fail safely
        corrupted = enc[:-4] + "AAAA"
        dec_corrupt = decrypt_api_key(corrupted, self.master_secret)
        self.assertEqual(dec_corrupt, corrupted, "Corrupted ciphertext should fail-safe without crashing")

    # -------------------------------------------------------------------------
    # 2. Fail-Closed Validation on Missing or Insecure Master Secrets
    # -------------------------------------------------------------------------
    def test_fail_closed_validation(self):
        # A. Empty key -> must raise InsecureSecretKeyError
        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("")

        # B. Too short key (<32 bytes) -> must raise InsecureSecretKeyError
        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("short-16-bytes!")

        # C. Known default keys -> must raise InsecureSecretKeyError
        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("ragflow_single_global_instance_master_secret_2026")

        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("ragflow")

        with self.assertRaises(InsecureSecretKeyError):
            validate_master_secret("infiniflow")

        # D. Encrypt with empty secret and no env var -> fails closed
        os.environ.pop("RAGFLOW_SECRET_KEY", None)
        with self.assertRaises(InsecureSecretKeyError):
            encrypt_api_key("some_secret", secret="")

    # -------------------------------------------------------------------------
    # 3. Cross-Language Compatibility: Python <-> Go Bidirectional Vectors
    # -------------------------------------------------------------------------
    def test_cross_language_compatibility(self):
        expected_plain = "cross-lang-test-secret-value-12345"

        # A. Vector generated by Go (utility.EncryptAPIKey with AES-256-GCM + HKDF):
        go_v2_vector = "enc:v2:nB4USVo0RRT4hDXHEFM71cQUXn7pQMO+yX8BCcYEy7Ti7onbWsiQWsGPdCItubMOkZFJwFGWbp9p9MzXgqg="
        dec_from_go = decrypt_api_key(go_v2_vector, self.master_secret)
        self.assertEqual(dec_from_go, expected_plain, "Python failed to decrypt Go AES-256-GCM HKDF ciphertext")

        # B. Python constant vector: verified to decrypt in both Python and Go
        py_v2_vector = "enc:v2:yqE1XB6mL4jEC7fDc+utp8iy4YFn6dtO2jHQVNvvhtPn2oceDAkD5S8mu6QeISVb0nDZB7n+i5V3+8AL+l4="
        dec_py_vector = decrypt_api_key(py_v2_vector, self.master_secret)
        self.assertEqual(dec_py_vector, expected_plain, "Python failed to decrypt its own constant vector")

        # C. Go legacy v1 vector (HMAC-SHA256 CTR) decrypted by Python:
        legacy_v1_vector = "enc:v1:MDEyMzQ1Njc4OWFiY2RlZi2J+E1szJ+OKGOCVomikPPcq0j8d0Yjn7GmJSVm2UwuvGA+XSQUssnHfH0HcjdVGcLw"
        dec_legacy = decrypt_api_key(legacy_v1_vector, self.master_secret)
        self.assertEqual(dec_legacy, expected_plain, "Python failed to decrypt legacy enc:v1: vector")

    # -------------------------------------------------------------------------
    # 4. Key Rotation: Decryption via Keyring
    # -------------------------------------------------------------------------
    def test_key_rotation_keyring(self):
        old_key = "old-master-secret-key-rotated-2025"
        new_key = "new-master-secret-key-current-2026"
        secret_val = "pre-rotation-confidential-secret"

        # Encrypted under old key
        enc_old = encrypt_api_key(secret_val, old_key)
        self.assertTrue(enc_old.startswith("enc:v2:"))

        # Configure environment with new primary key and old key in rotation list
        os.environ["RAGFLOW_SECRET_KEY"] = new_key
        os.environ["RAGFLOW_SECRET_KEYS_ROTATION"] = f"other-key-1,{old_key},other-key-2"

        # decrypt_api_key without explicit secret uses environment keyring
        dec_val = decrypt_api_key(enc_old)
        self.assertEqual(dec_val, secret_val, "Key rotation keyring failed to decrypt ciphertext from retired key")

    # -------------------------------------------------------------------------
    # 5. Deny-by-Default Credential Scope
    # -------------------------------------------------------------------------
    def test_deny_by_default_in_credentials(self):
        raw_config = {
            "source": "jira",
            "name": "Corporate Jira",
            "sync_deleted_files": True,
            "credentials": {
                "instance_url": "https://company.atlassian.net",   # public identifier
                "jira_user_email": "admin@company.com",            # public identifier
                "jira_api_token": "ATATT3xFfGF0SECRET_TOKEN",       # sensitive -> must be encrypted
                "custom_oauth_client_secret": "xyz123secret",       # sensitive -> must be encrypted
                "unlisted_future_crm_field": "confidential_value",  # unknown -> must be encrypted (fail-safe!)
            },
            "non_cred_unrelated": "public_data"
        }

        enc_config = encrypt_connector_config(raw_config)
        creds = enc_config["credentials"]

        self.assertEqual(creds["instance_url"], "https://company.atlassian.net")
        self.assertEqual(creds["jira_user_email"], "admin@company.com")
        self.assertTrue(creds["jira_api_token"].startswith("enc:v2:"))
        self.assertTrue(creds["custom_oauth_client_secret"].startswith("enc:v2:"))
        self.assertTrue(creds["unlisted_future_crm_field"].startswith("enc:v2:"))
        self.assertEqual(enc_config["non_cred_unrelated"], "public_data")

        # Decrypt
        dec_config = decrypt_connector_config(enc_config)
        self.assertEqual(dec_config, raw_config)

    # -------------------------------------------------------------------------
    # 6. Deny-by-Default for rest_api auth_config and headers
    # -------------------------------------------------------------------------
    def test_deny_by_default_auth_config_and_headers(self):
        rest_api_config = {
            "source": "rest_api",
            "auth_config": {
                "api_key": "raw-auth-config-api-key-888",
                "custom_header_secret": "sec-999-auth",
                "auth_mode": "bearer",
            },
            "headers": {
                "Authorization": "Bearer super-secret-jwt-token-777",
                "X-API-Key": "secret-header-key-value",
            }
        }

        enc_config = encrypt_connector_config(rest_api_config)
        self.assertTrue(enc_config["auth_config"]["api_key"].startswith("enc:v2:"))
        self.assertTrue(enc_config["auth_config"]["custom_header_secret"].startswith("enc:v2:"))
        self.assertTrue(enc_config["headers"]["Authorization"].startswith("enc:v2:"))
        self.assertTrue(enc_config["headers"]["X-API-Key"].startswith("enc:v2:"))

        # Masking for API response
        masked = mask_connector_config(enc_config)
        self.assertEqual(masked["auth_config"]["api_key"], "********")
        self.assertEqual(masked["auth_config"]["custom_header_secret"], "********")
        self.assertEqual(masked["headers"]["Authorization"], "********")
        self.assertEqual(masked["headers"]["X-API-Key"], "********")

        # Decrypting
        decrypted = decrypt_connector_config(enc_config)
        self.assertEqual(decrypted["auth_config"]["api_key"], "raw-auth-config-api-key-888")
        self.assertEqual(decrypted["headers"]["Authorization"], "Bearer super-secret-jwt-token-777")

    # -------------------------------------------------------------------------
    # 7. URL Credentials Sanitization and Rest-Encryption
    # -------------------------------------------------------------------------
    def test_url_credentials_sanitization_and_encryption(self):
        cfg = {
            "rss_url": "https://feed.example.com/rss?token=secret_query_token_123&category=news",
            "sitemap_url": "https://admin:my_secret_http_pass@sitemap.example.com/sitemap.xml",
            "credentials": {
                "instance_url": "https://service-user:p@ssword999@jira.corp.local",
                "client_id": "public-client-id-123",
            }
        }

        # 1. Detection
        self.assertTrue(has_embedded_url_credentials(cfg["rss_url"]))
        self.assertTrue(has_embedded_url_credentials(cfg["sitemap_url"]))
        self.assertTrue(has_embedded_url_credentials(cfg["credentials"]["instance_url"]))
        self.assertFalse(has_embedded_url_credentials("https://safe.example.com/feed.xml"))

        # 2. Masking
        masked = mask_connector_config(cfg)
        self.assertEqual(masked["rss_url"], "https://feed.example.com/rss?token=********&category=news")
        self.assertEqual(masked["sitemap_url"], "https://admin:********@sitemap.example.com/sitemap.xml")
        self.assertEqual(masked["credentials"]["instance_url"], "https://service-user:********@jira.corp.local")
        self.assertEqual(masked["credentials"]["client_id"], "public-client-id-123")

        # 3. Encryption at rest
        encrypted = encrypt_connector_config(cfg)
        self.assertTrue(encrypted["rss_url"].startswith("enc:v2:"))
        self.assertTrue(encrypted["sitemap_url"].startswith("enc:v2:"))
        self.assertTrue(encrypted["credentials"]["instance_url"].startswith("enc:v2:"))

        # 4. Decryption recovers original URLs
        decrypted = decrypt_connector_config(encrypted)
        self.assertEqual(decrypted["rss_url"], cfg["rss_url"])
        self.assertEqual(decrypted["sitemap_url"], cfg["sitemap_url"])
        self.assertEqual(decrypted["credentials"]["instance_url"], cfg["credentials"]["instance_url"])

    # -------------------------------------------------------------------------
    # 8. Masking for Safe API Responses
    # -------------------------------------------------------------------------
    def test_masking_for_api_responses(self):
        raw_config = {
            "source": "zendesk",
            "credentials": {
                "zendesk_subdomain": "mycompany",
                "zendesk_email": "agent@mycompany.com",
                "zendesk_token": "secret_api_token_here",
                "some_obscure_secret": "top_secret_value",
            }
        }
        enc_config = encrypt_connector_config(raw_config)

        # Test masking on encrypted config (what DB returns)
        masked_from_enc = mask_connector_config(enc_config)
        m_creds = masked_from_enc["credentials"]
        self.assertEqual(m_creds["zendesk_subdomain"], "mycompany")
        self.assertEqual(m_creds["zendesk_email"], "agent@mycompany.com")
        self.assertEqual(m_creds["zendesk_token"], "********")
        self.assertEqual(m_creds["some_obscure_secret"], "********")

        # Also test masking on plaintext config
        masked_from_plain = mask_connector_config(raw_config)
        self.assertEqual(masked_from_plain["credentials"]["zendesk_token"], "********")
        self.assertEqual(masked_from_plain["credentials"]["some_obscure_secret"], "********")

    # -------------------------------------------------------------------------
    # 9. Safe Update / Merge Pattern (Preserves Existing Secrets)
    # -------------------------------------------------------------------------
    def test_merge_updated_connector_config(self):
        stored_raw_config = {
            "source": "bitbucket",
            "credentials": {
                "username": "bb_admin",
                "app_password": "real_secret_password_12345",
                "account_id": "acc-9988",
            },
            "refresh_freq": 5
        }
        stored_enc_config = encrypt_connector_config(stored_raw_config)
        original_enc_password = stored_enc_config["credentials"]["app_password"]
        self.assertTrue(original_enc_password.startswith("enc:v2:"))

        # Scenario A: UI sends "********" mask placeholder
        incoming_ui_payload = {
            "credentials": {
                "username": "bb_admin",
                "app_password": "********",
                "account_id": "acc-9988",
            },
            "refresh_freq": 15
        }
        merged = merge_updated_connector_config(stored_enc_config, incoming_ui_payload)
        self.assertEqual(merged["refresh_freq"], 15)
        self.assertEqual(merged["credentials"]["app_password"], original_enc_password)

        decrypted_merged = decrypt_connector_config(merged)
        self.assertEqual(decrypted_merged["credentials"]["app_password"], "real_secret_password_12345")

        # Scenario B: User provides a real new password
        incoming_new_pw_payload = {
            "credentials": {
                "username": "bb_admin",
                "app_password": "brand_new_password_99999",
                "account_id": "acc-9988",
            },
            "refresh_freq": 15
        }
        merged_new_pw = merge_updated_connector_config(stored_enc_config, incoming_new_pw_payload)
        new_enc_password = merged_new_pw["credentials"]["app_password"]
        self.assertTrue(new_enc_password.startswith("enc:v2:"))
        self.assertNotEqual(new_enc_password, original_enc_password)

        decrypted_new = decrypt_connector_config(merged_new_pw)
        self.assertEqual(decrypted_new["credentials"]["app_password"], "brand_new_password_99999")

        # Scenario C: UI sends empty string for existing secret
        incoming_empty_pw = {
            "credentials": {
                "username": "bb_admin",
                "app_password": "",
                "account_id": "acc-9988",
            }
        }
        merged_empty = merge_updated_connector_config(stored_enc_config, incoming_empty_pw)
        self.assertEqual(merged_empty["credentials"]["app_password"], original_enc_password)

    # -------------------------------------------------------------------------
    # 10. Syncer Decryption and OAuth Token Refresh Re-encryption
    # -------------------------------------------------------------------------
    def test_syncer_decryption_and_oauth_refresh(self):
        stored_config = {
            "source": "gmail",
            "credentials": {
                "client_id": "gmail_client_id_123.apps.googleusercontent.com",
                "client_secret": "gmail_secret_456",
                "refresh_token": "original_refresh_token_789",
                "access_token": "expired_access_token_000",
            }
        }
        db_config = encrypt_connector_config(stored_config)
        self.assertTrue(db_config["credentials"]["client_secret"].startswith("enc:v2:"))
        self.assertTrue(db_config["credentials"]["refresh_token"].startswith("enc:v2:"))
        self.assertTrue(db_config["credentials"]["access_token"].startswith("enc:v2:"))

        # 1. Syncer starts: decrypts config to connect to Google API
        syncer_config = decrypt_connector_config(db_config)
        self.assertEqual(syncer_config["credentials"]["client_secret"], "gmail_secret_456")
        self.assertEqual(syncer_config["credentials"]["refresh_token"], "original_refresh_token_789")

        # 2. Syncer receives new OAuth access token from Google OAuth endpoint:
        refreshed_access_token = "brand_new_refreshed_access_token_from_google_api_999"
        update_payload = {
            "credentials": {
                "access_token": refreshed_access_token,
            }
        }

        # 3. Syncer writes back to DB via merge_updated_connector_config:
        updated_db_config = merge_updated_connector_config(db_config, update_payload)

        new_enc_token = updated_db_config["credentials"]["access_token"]
        self.assertTrue(new_enc_token.startswith("enc:v2:"), f"Refreshed token was saved as plaintext! Got: {new_enc_token}")
        self.assertNotEqual(new_enc_token, refreshed_access_token)

        recovered = decrypt_connector_config(updated_db_config)
        self.assertEqual(recovered["credentials"]["access_token"], refreshed_access_token)

    # -------------------------------------------------------------------------
    # 11. Migration CLI: Find Unencrypted, Rollback Reverse, Key Rotation
    # -------------------------------------------------------------------------
    def test_migration_cli_helpers(self):
        plaintext_cfg = {
            "credentials": {
                "instance_url": "https://example.com",
                "jira_api_token": "raw_token_xyz",
                "nested_auth": {
                    "private_key": "raw_key_abc",
                    "public_field": "visible"
                }
            }
        }
        # 1. Plaintext config has 2 unencrypted fields
        unenc = find_unencrypted_keys(plaintext_cfg)
        self.assertIn("credentials.jira_api_token", unenc)
        self.assertIn("credentials.nested_auth.private_key", unenc)
        self.assertNotIn("credentials.instance_url", unenc)

        # 2. Encrypted config has 0 unencrypted fields
        enc_cfg = encrypt_connector_config(plaintext_cfg)
        self.assertEqual(len(find_unencrypted_keys(enc_cfg)), 0)

        # 3. Encrypted config has 2 encrypted fields
        enc_fields = find_encrypted_keys(enc_cfg)
        self.assertIn("credentials.jira_api_token", enc_fields)
        self.assertIn("credentials.nested_auth.private_key", enc_fields)

        # 4. Reverse rollback restores exact plaintext
        reversed_cfg = decrypt_connector_config(enc_cfg)
        self.assertEqual(reversed_cfg, plaintext_cfg)
        self.assertEqual(len(find_encrypted_keys(reversed_cfg)), 0)

    # -------------------------------------------------------------------------
    # 12. Real Connector Blueprint: HTTP Leak Regression via connector_api.py
    # -------------------------------------------------------------------------
    def test_real_connector_blueprint_leak_regression(self):
        """
        Load the real connector_api.py blueprint via importlib (heavy deps stubbed),
        register it on a clean Quart test app, exercise GET /api/v1/connectors/<id>
        through the real _format_connector_response() path, and confirm no plaintext
        credential leaks. Then run mutation verification: patch mask_connector_config
        to identity function and confirm the test FAILS (proving the guard is real).
        """
        import importlib.util
        import sys
        import types

        # ------------------------------------------------------------------
        # 1. Secrets we will store encrypted in the fake DB record.
        # ------------------------------------------------------------------
        raw_api_key = "super_confidential_crm_bearer_token_xyz_999"
        raw_client_secret = "raw_oauth_client_secret_abc_456"
        raw_http_pass = "http_pass_777"
        raw_db_config = {
            "credentials": {
                "instance_url": f"https://admin:{raw_http_pass}@crm.corp.internal",
                "client_id": "public_cid_123",
                "client_secret": raw_client_secret,
            },
            "auth_config": {
                "api_key": raw_api_key,
            },
            "headers": {
                "Authorization": f"Bearer {raw_api_key}",
            },
        }
        stored_enc_config = encrypt_connector_config(raw_db_config)

        # ------------------------------------------------------------------
        # 2. Build the minimal stub chain that connector_api.py needs.
        #    We do NOT import api.apps (calls settings.init_settings()).
        # ------------------------------------------------------------------
        import api.utils.key_crypto as _real_key_crypto

        # Fake connector record
        class _FakeConn:
            def to_dict(self):
                return {
                    "id": "conn-fake-001",
                    "tenant_id": "tenant-123",
                    "name": "Production Salesforce CRM",
                    "source": "salesforce",
                    "config": stored_enc_config,
                }

        class _FakeConnectorService:
            @staticmethod
            def accessible(connector_id, user_id):
                return True

            @staticmethod
            def get_by_id(connector_id):
                return True, _FakeConn()

        class _FakeSyncLogsService:
            @staticmethod
            def list_sync_tasks(connector_id, page, page_size):
                return [], 0

        from common.constants import RetCode as _RealRetCode
        from quart import jsonify as _jsonify

        def _fake_get_json_result(data=None, message="success", code=0):
            return _jsonify({"code": code, "message": message, "data": data})

        def _fake_get_data_error_result(code=102, message="Data error"):
            return _jsonify({"code": code, "message": message, "data": False})

        from functools import wraps as _wraps

        def _fake_login_required(func=None, auth_types=None):
            def decorator(f):
                @_wraps(f)
                async def wrapper(*args, **kwargs):
                    if asyncio.iscoroutinefunction(f):
                        return await f(*args, **kwargs)
                    return f(*args, **kwargs)
                return wrapper
            if func is None:
                return decorator
            return decorator(func)

        class _FakeCurrentUser:
            id = "user-test-001"

        def _make_dummy(name, **attrs):
            m = types.ModuleType(name)
            m.__dict__.update(attrs)
            return m

        stubs = {
            "google_auth_oauthlib": _make_dummy("google_auth_oauthlib"),
            "google_auth_oauthlib.flow": _make_dummy("google_auth_oauthlib.flow", Flow=None),
            "box_sdk_gen": _make_dummy("box_sdk_gen",
                BoxOAuth=None, OAuthConfig=None, GetAuthorizeUrlOptions=None),
            "rag": _make_dummy("rag"),
            "rag.utils": _make_dummy("rag.utils"),
            "rag.utils.redis_conn": _make_dummy("rag.utils.redis_conn", REDIS_CONN=None),
            "common.data_source": _make_dummy("common.data_source"),
            "common.data_source.config": _make_dummy(
                "common.data_source.config",
                GOOGLE_DRIVE_WEB_OAUTH_REDIRECT_URI="",
                GMAIL_WEB_OAUTH_REDIRECT_URI="",
                BOX_WEB_OAUTH_REDIRECT_URI="",
                DocumentSource=None,
            ),
            "common.data_source.google_util": _make_dummy("common.data_source.google_util"),
            "common.data_source.google_util.constant": _make_dummy(
                "common.data_source.google_util.constant",
                WEB_OAUTH_POPUP_TEMPLATE="",
                GOOGLE_SCOPES=[],
            ),
            "common.misc_utils": _make_dummy("common.misc_utils",
                get_uuid=lambda: "fake-uuid-1234"),
            "api.db": _make_dummy("api.db",
                InputType=type("InputType", (), {"POLL": "poll"})),
            "api.db.services.connector_service": _make_dummy(
                "api.db.services.connector_service",
                ConnectorService=_FakeConnectorService,
                SyncLogsService=_FakeSyncLogsService,
                ConnectorAuthorizationError=Exception,
            ),
            "api.utils.api_utils": _make_dummy(
                "api.utils.api_utils",
                get_json_result=_fake_get_json_result,
                get_data_error_result=_fake_get_data_error_result,
                get_request_json=None,
                validate_request=lambda *a, **kw: (lambda f: f),
            ),
            "api.utils.pagination_utils": _make_dummy(
                "api.utils.pagination_utils",
                DEFAULT_PAGE=1, DEFAULT_PAGE_SIZE=20,
                validate_rest_api_page=lambda x: int(x),
                validate_rest_api_page_size=lambda x: int(x),
            ),
            "common.constants": _make_dummy(
                "common.constants",
                FileSource=None,
                RetCode=_RealRetCode,
                TaskStatus=type("TaskStatus", (), {
                    "CANCEL": "CANCEL", "SCHEDULE": "SCHEDULE", "UNSTART": "UNSTART"}),
            ),
            "api.utils.key_crypto": _real_key_crypto,
            "api.apps": _make_dummy(
                "api.apps",
                login_required=_fake_login_required,
                current_user=_FakeCurrentUser(),
            ),
        }

        # ------------------------------------------------------------------
        # 3. Install stubs → exec module → restore sys.modules.
        # ------------------------------------------------------------------
        saved = {}
        for k, v in stubs.items():
            saved[k] = sys.modules.get(k)
            sys.modules[k] = v

        connector_api_path = os.path.abspath(os.path.join(
            os.path.dirname(__file__), "..", "api", "apps", "restful_apis", "connector_api.py"
        ))

        try:
            from quart import Blueprint, Quart
            mod_name = "api.apps.restful_apis.connector_api"
            spec = importlib.util.spec_from_file_location(mod_name, connector_api_path)
            mod = importlib.util.module_from_spec(spec)
            mod.manager = Blueprint("connector_api", mod_name)
            sys.modules[mod_name] = mod
            spec.loader.exec_module(mod)
        finally:
            for k, orig in saved.items():
                if orig is None:
                    sys.modules.pop(k, None)
                else:
                    sys.modules[k] = orig
            sys.modules.pop("api.apps.restful_apis.connector_api", None)

        # ------------------------------------------------------------------
        # 4. Register blueprint on isolated test Quart app.
        # ------------------------------------------------------------------
        test_app = Quart("test_real_blueprint")
        test_app.config["TESTING"] = True
        test_app.config["SECRET_KEY"] = "test-secret"
        test_app.register_blueprint(mod.manager, url_prefix="/api/v1")

        # ------------------------------------------------------------------
        # 5. Run GET handler: assert no plaintext leaks.
        # ------------------------------------------------------------------
        async def _assert_no_leaks():
            async with test_app.test_client() as client:
                resp = await client.get("/api/v1/connectors/conn-fake-001")
                self.assertEqual(resp.status_code, 200,
                    f"Handler returned {resp.status_code}")
                body = await resp.get_data(as_text=True)

                self.assertNotIn(raw_api_key, body,
                    f"RAW API KEY leaked:\n{body}")
                self.assertNotIn(raw_client_secret, body,
                    f"RAW CLIENT SECRET leaked:\n{body}")
                self.assertNotIn(raw_http_pass, body,
                    f"RAW HTTP PASSWORD leaked:\n{body}")

                import json as _json
                payload = _json.loads(body)
                cfg = payload["data"]["config"]
                self.assertEqual(cfg["credentials"]["client_secret"], "********")
                self.assertEqual(cfg["credentials"]["instance_url"],
                    "https://admin:********@crm.corp.internal")
                self.assertEqual(cfg["auth_config"]["api_key"], "********")
                self.assertEqual(cfg["headers"]["Authorization"], "********")

        asyncio.run(_assert_no_leaks())

        # ------------------------------------------------------------------
        # 6. MUTATION VERIFICATION: remove masking in connector_api → test MUST fail.
        # ------------------------------------------------------------------
        _orig_mod_mask = getattr(mod, "mask_connector_config", None)
        _orig_crypto_mask = _real_key_crypto.mask_connector_config
        mod.mask_connector_config = lambda cfg, *a, **kw: cfg  # identity bypass in connector_api
        _real_key_crypto.mask_connector_config = lambda cfg, *a, **kw: cfg
        mutation_caught = False
        try:
            asyncio.run(_assert_no_leaks())
        except AssertionError as exc:
            mutation_caught = True
            print(f"\n[MUTATION OK] masking removed in connector_api.py -> assertion correctly failed:\n  {exc}")
        finally:
            if _orig_mod_mask:
                mod.mask_connector_config = _orig_mod_mask
            _real_key_crypto.mask_connector_config = _orig_crypto_mask

        self.assertTrue(mutation_caught,
            "MUTATION GUARD FAILED: removing mask_connector_config did NOT cause test to fail")

    # -------------------------------------------------------------------------
    # 13. URL Round-Trip PATCH: masked URL must preserve original secret
    # -------------------------------------------------------------------------
    def test_url_roundtrip_patch_masked_url(self):
        """
        PATCH contract: if the UI sends back a masked URL
        (https://user:********@host?token=********) the stored original
        secret must be preserved — no data is lost or corrupted.
        """
        original_url = (
            "https://service-user:p@ssw0rd!Really$ecret"
            "@jira.corp.local/api?token=s3cr3t-tok3n"
        )
        original_password = "p@ssw0rd!Really$ecret"
        original_token = "s3cr3t-tok3n"

        raw_config = {
            "credentials": {
                "instance_url": original_url,
                "client_id": "public-client-id",
            }
        }
        stored_enc = encrypt_connector_config(raw_config)

        # Mask as returned to UI
        masked = mask_connector_config(stored_enc)
        masked_url = masked["credentials"]["instance_url"]

        # Confirm masking worked
        self.assertNotIn(original_password, masked_url,
            "Password not masked in instance_url")
        self.assertNotIn(original_token, masked_url,
            "Token not masked in instance_url")
        self.assertIn("********", masked_url)

        # UI sends back the masked URL unchanged in PATCH body
        patch_payload = {
            "credentials": {
                "instance_url": masked_url,
                "client_id": "public-client-id",
            }
        }

        merged = merge_updated_connector_config(stored_enc, patch_payload)

        # After merge, value must still be encrypted (not the bare masked sentinel)
        merged_url_val = merged["credentials"]["instance_url"]
        self.assertTrue(
            merged_url_val.startswith("enc:v2:"),
            f"Expected enc:v2: after PATCH with masked URL, got: {merged_url_val!r}"
        )

        # Decrypting must recover the ORIGINAL full URL
        recovered = decrypt_connector_config(merged)
        self.assertEqual(
            recovered["credentials"]["instance_url"],
            original_url,
            f"URL round-trip FAILED — original secret was lost!\n"
            f"  original : {original_url!r}\n"
            f"  recovered: {recovered['credentials']['instance_url']!r}"
        )

    # -------------------------------------------------------------------------
    # 14. AI Provider Radius of Impact: Legacy enc:v1: Decryption & Key Rotation
    # -------------------------------------------------------------------------
    def test_ai_provider_legacy_v1_and_rotation_behavior(self):
        """
        ai_provider_service uses key_crypto.py for LLM API keys.
        Existing keys in production were encrypted under legacy enc:v1: (HMAC-SHA256 CTR).
        This test proves:
        1. An existing enc:v1: key decrypts properly with the original secret.
        2. When rotated to a new primary secret (with old key in RAGFLOW_SECRET_KEYS_ROTATION),
           the enc:v1: key continues to decrypt seamlessly.
        3. When a new key is encrypted, it automatically gets modern enc:v2: (AES-256-GCM).
        4. If secret changes without old key in rotation list, decryption fails safely
           without crashing, returning the ciphertext and logging an error.
        """
        old_ai_secret = "legacy-ai-provider-secret-key-32b!"
        raw_openai_key = "sk-proj-super-confidential-openai-api-key-12345"

        # Known enc:v1: vector generated with old_ai_secret
        # iv: 16 bytes "0123456789abcdef", payload encrypted with HMAC-CTR using old_ai_secret
        # We can construct or verify via decrypt_api_key
        legacy_v1_vector = "enc:v1:MDEyMzQ1Njc4OWFiY2RlZi2J+E1szJ+OKGOCVomikPPcq0j8d0Yjn7GmJSVm2UwuvGA+XSQUssnHfH0HcjdVGcLw"
        expected_plain = "cross-lang-test-secret-value-12345"

        # 1. Decrypt with matching master secret (self.master_secret)
        decrypted_primary = decrypt_api_key(legacy_v1_vector, self.master_secret)
        self.assertEqual(decrypted_primary, expected_plain, "Failed to decrypt legacy v1 with primary key")

        # 2. Key rotation: master secret changes to new_secret, old key moved to rotation list
        new_secret = "brand-new-primary-key-32bytes-ok!"
        os.environ["RAGFLOW_SECRET_KEY"] = new_secret
        os.environ["RAGFLOW_SECRET_KEYS_ROTATION"] = f"unrelated-key,{self.master_secret}"

        # decrypt_api_key with no explicit secret should use keyring and succeed
        decrypted_rotated = decrypt_api_key(legacy_v1_vector)
        self.assertEqual(decrypted_rotated, expected_plain, "Failed to decrypt legacy v1 via rotation keyring")

        # 3. New encryption under new primary key produces enc:v2:
        new_enc = encrypt_api_key("sk-proj-new-key-12345")
        self.assertTrue(new_enc.startswith("enc:v2:"), f"Expected enc:v2:, got: {new_enc}")
        self.assertEqual(decrypt_api_key(new_enc), "sk-proj-new-key-12345")

        # 4. Unknown key: neither primary nor rotation matches -> fails safely, returns ciphertext
        os.environ["RAGFLOW_SECRET_KEY"] = "completely-different-key-32bytes!!"
        os.environ.pop("RAGFLOW_SECRET_KEYS_ROTATION", None)
        failed_dec = decrypt_api_key(legacy_v1_vector)
        self.assertEqual(failed_dec, legacy_v1_vector, "Unknown key should safely return ciphertext without crash")


if __name__ == "__main__":
    unittest.main()


