name: Deploy Appsmith

on:
  push:
    branches:
      - main
    paths:
      - 'appsmith/**'   # Запускать только если есть изменения в папке appsmith

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Appsmith with Docker Compose
        working-directory: swipies__ai_/appsmith/deploy/docker
        run: |
          docker-compose pull
          docker-compose down
          docker-compose up -d

      - name: Verify containers
        run: docker ps -a
